apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongo-cfg
data:
  mongo-init.js: |
    db.createUser(
      {
          user: "username",
          pwd: "password",
          roles: [
              {
                  role: "readWrite",
                  db: "integration-service-db"
              }
          ]
      }
    );
