apiVersion: v1
kind: Service
metadata:
  name: integration-service-api-2
spec:
  type: LoadBalancer
  selector:
    app: integration-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  
