apiVersion: v1
kind: Secret
metadata:
  name: integration-service-api-secrets
type: Opaque
data:
  SERVER_SECRET: UHBLRmhQS0pZMmVmVHNOOVZrQjdXTnRZVWhYOVV0YWE=
  API_KEY: OTRGNUJBNDktMTJCNi00RTQ1LUE0ODctQkY5MUM0NDIyNzZE

